SELECT * FROM SCLOAN.PP_ACCRUED_PAYMENTS PA WHERE PA.PPA_PYMT_PLAN_ID = 297428 

SELECT * FROM SCLOAN.PP_OVERDUE PO WHERE PO.PPO_PLAN_ID = 297428 

SELECT * FROM SCLOAN.PP_INSTALLMENT PI WHERE PI.INST_PLAN_ID = 297428 

SELECT PA.* FROM SCHESAP.ACCOUNT_EXTERNAL_REF EXT WHERE EXT.ACEXT_BRANCH_CODE = 1420 AND EXT.ACEXT_ACCOUNT_NUMBER = 1000151
and pp.ppl_plan_id = pa.ppa_plan_id and ext.acext_account_id = pp.ppl_acc_id

SELECT * FROM SCHESAP.ACCOUNT_INFO AI WHERE AI.ACINF_ACCOUNT_ID = 49631410

SELECT * FROM SCHESAP.ACCOUNT_BALANCES AB WHERE AB.ACBLN_ACCOUNT_ID = 49631410

SELECT * FROM SCLOAN.LAM_LOAN_INFO LI WHERE LI.LOAN_ACC_ID = 49631410