UPDATE "SCLOAN"."LFN_KKB_CUST_INCOME_INFO" SET "CUI_TRANSFERRED_VKN" = null WHERE "CUI_STATUS" = 'A';
commit;

UPDATE "SCLOAN"."LFN_KKB_CUST_INCOME_INFO" SET "CUI_TRANSFERRED_VKN" = '3940386280' WHERE "CUI_ID" = 6892;
UPDATE "SCLOAN"."LFN_KKB_CUST_INCOME_INFO" SET "CUI_TRANSFERRED_VKN" = '6600440687' WHERE "CUI_ID" = 7010;
UPDATE "SCLOAN"."LFN_KKB_CUST_INCOME_INFO" SET "CUI_TRANSFERRED_VKN" = '6600440687' WHERE "CUI_ID" = 7011;
UPDATE "SCLOAN"."LFN_KKB_CUST_INCOME_INFO" SET "CUI_TRANSFERRED_VKN" = '6600440687' WHERE "CUI_ID" = 7012;


UPDATE "SCLOAN"."LFN_KKB_NOTIFICATION" SET "NOT_STATUS" = 'A' WHERE "NOT_ID" = '132087'; 
UPDATE "SCLOAN"."LFN_KKB_NOTIFICATION" SET "NOT_STATUS" = 'A' WHERE "NOT_ID" = '132049'; 
UPDATE "SCLOAN"."LFN_KKB_NOTIFICATION" SET "NOT_STATUS" = 'A' WHERE "NOT_ID" = '132090'; 
UPDATE "SCLOAN"."LFN_KKB_NOTIFICATION" SET "NOT_STATUS" = 'A' WHERE "NOT_ID" = '132109';
UPDATE "SCLOAN"."LFN_KKB_NOTIFICATION" SET "NOT_STATUS" = 'A' WHERE "NOT_ID" = '132125'; 
COMMIT;

DELETE "SCLOAN"."LFN_KKB_NOTIFICATION" WHERE "NOT_ID" = 131874; 
COMMIT;
