select T1.RESMI_UNVAN, T2.REFERANS_KIMLIK_NO
from STG.MBY_TUZEL_KIMLIK T1, MBY_REFERANS_KIMLIK_NO T2 where
T1.MUSTERI_NO = T2.MUSTERI_NO AND T2.REFERANS_KIMLIK_TIPI = '1060001' AND
T1.MUSTERI_NO = '327358304';


MUSTERI_NO	1	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
RESMI_UNVAN	2	Y	N	VARCHAR2 (1000 bytes)	<LONG>	HYBRID
TERCIH_EDILEN_UNVAN	3	Y	N	VARCHAR2 (1000 bytes)	<LONG>	NONE
KURULUS_TARIHI	4	Y	N	DATE (7 bytes)	<LONG>	NONE
KURULUS_YERI	5	Y	N	CHAR (12 bytes)	<LONG>	NONE
KURULU_OLDUGU_ULKE	6	Y	N	CHAR (12 bytes)	<LONG>	FREQUENCY
SIRKET_TIPI	7	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
VERGI_DAIRESI_KODU	8	Y	N	NUMBER (22 bytes)	<LONG>	NONE
KAYIT_KURUM_TIPI	9	Y	N	NUMBER (22 bytes)	<LONG>	NONE
KAYIT_KURUM_KODU	10	Y	N	VARCHAR2 (20 bytes)	<LONG>	NONE
KAYIT_KURUM_SICIL_NO	11	Y	N	VARCHAR2 (20 bytes)	<LONG>	NONE
CALISAN_SAYISI	12	Y	N	NUMBER (22 bytes)	<LONG>	NONE
SWIFT_KODU	13	Y	N	VARCHAR2 (20 bytes)	<LONG>	NONE
VKN_TIPI	14	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ISLEM_KAYIT_ID	15	Y	N	NUMBER (22 bytes)	<LONG>	NONE
SRC_DT	16	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
UPD_DT	17	Y	N	DATE (7 bytes)	<LONG>	NONE
GIIN	18	Y	N	VARCHAR2 (20 bytes)	<LONG>	NONE
FAAL_TERK_DURUMU	19	Y	N	NUMBER (22 bytes)	<LONG>	NONE
IS_BIRAKMA_TARIHI	20	Y	N	DATE (7 bytes)	<LONG>	NONE
POTANSIYEL	21	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ISE_BASLAMA_TARIHI	22	Y	N	DATE (7 bytes)	<LONG>	NONE


MUSTERI_NO	1	Y	N	NUMBER (22 bytes)	<LONG>	NONE
REFERANS_KIMLIK_TIPI	2	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
REFERANS_KIMLIK_NO	3	Y	N	VARCHAR2 (20 bytes)	<LONG>	HYBRID
ISLEM_KAYIT_ID	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
SRC_DT	5	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
UPD_DT	6	Y	N	DATE (7 bytes)	<LONG>	NONE
SYS_STS2SH0Q2B3G5FEE4DRBDMXT#5	0	Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STS76Y4SFORSXD7A$KO_RUF1R2	0	Y	N	NUMBER (22 bytes)	<LONG>	NONE