SELECT 
SNPST_DT,
UPD_DT,
DOS_DOSYANUM,
DOS_ISIM,
DOS_MUSTERINO,
DOS_BAKIYE,
DOS_ACILIS_BAKIYE,
DOS_ACILKD,
DOS_ACILTAR_YYAG_DT,
DOS_VADEBASTAR_YYAG_DT,
DOS_VADEBITTAR_YYAG_DT
FROM 
ODS.DOSYAREC_DVZ 
WHERE
( 
DOS_DOSYANUM = '1111DG091555' OR
DOS_DOSYANUM = '1111DA600228' OR
DOS_DOSYANUM = '3399DA090657' OR
DOS_DOSYANUM = '1278DA300017' OR
DOS_DOSYANUM = '2430DG700018' OR
DOS_DOSYANUM = '3399DA090513' OR
DOS_DOSYANUM = '4399DG700017' OR
DOS_DOSYANUM = '4398DG700029' OR
DOS_DOSYANUM = '1392DG090069' OR
DOS_DOSYANUM = '4399DG500018' OR
DOS_DOSYANUM = '1392DA090259' OR
DOS_DOSYANUM = '1255DA400042' OR
DOS_DOSYANUM = '1254DA312301' OR
DOS_DOSYANUM = '1278DA300017' OR
DOS_DOSYANUM = '1256DA094289' OR
DOS_DOSYANUM = '1235DA090009' OR
DOS_DOSYANUM = '1444DA090415' OR
DOS_DOSYANUM = '1444DA090414' OR
DOS_DOSYANUM = '1254DA312631' OR
DOS_DOSYANUM = '1254DA312701' OR
DOS_DOSYANUM = '6125DA090019') AND 
SNPST_DT >= to_date('2019-04-01', 'YYYY-MM-DD');


SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	NONE
ODS_MUSTERI_NO	4	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
ODS_SUBE_KODU	5	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
ODS_HESAP_NO	6	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
ODS_TELNO	7	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
ODS_DURUM_KODU	8	Y	N	VARCHAR2 (10 bytes)	<LONG>	FREQUENCY
ODS_MUHASEBE_KODU	9	Y	N	VARCHAR2 (10 bytes)	<LONG>	FREQUENCY
ODS_DOVIZ_CINSI	10	Y	N	CHAR (3 bytes)	<LONG>	FREQUENCY
ODS_KRD_KODU	11	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
ODS_KRD_EK_KODU	12	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
ODS_KRD_KONTROL_HARFI	13	Y	N	CHAR (1 bytes)	<LONG>	NONE
ODS_GUNSONU_BAKIYE	14	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
ODS_BAKIYE	15	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
DOSNO_SBKD	16	Y	N	VARCHAR2 (4 bytes)	<LONG>	HYBRID
DOSNO_SIRANO	17	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DOSNO_TIPI	18	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DOS_ACILIS_BAKIYE	19	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_ACILKD	20	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DOS_ACILTAR_YYAG_DT	21	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_ARACI_SBKD	22	Y	N	VARCHAR2 (4 bytes)	<LONG>	HYBRID
DOS_AYS_ACILKD1	23	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DOS_AYS_FAIZ_DEVRESI	24	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DOS_AYS_FAIZ_KODU	25	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DOS_AYS_FAIZ_ORANI	26	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_AYS_KRE_GEL_REESTUT_T...	27	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
DOS_AYS_KRE_GID_REESTUT_T...	28	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_AYS_KRE_TAHAKKUK_ATIL...	29	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_AYS_KRE_TAHAKKUK_ATIL...	30	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_AYS_KRE_TAHAKKUK_TAHS...	31	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_AYS_KRE_TAHAKKUK_TAHS...	32	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_AYS_SON_FAIZ_YYAG_DT	33	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_AYS_VADE_BITTAR_YYAG_...	34	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_AYSONU_BAKIYE	35	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
DOS_AYSONU_REESTAR_YYAG_D...	36	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
DOS_BAKIYE	37	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
DOS_BAKIYE_DEGISTAR_YYAG_...	38	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_BATCH_BAKIYE	39	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_DEVIR_GEL_REES_DVTUT	40	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_DEVIR_GEL_REES_REFNO	41	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_DEVIR_GID_REES_REFNO	42	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_DEVIR_KODU	43	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DOS_DEVIR_TAHSIL_DVTUT	44	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_DUBPARM1	45	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_DUBPARM2	46	Y	N	VARCHAR2 (4 bytes)	<LONG>	NONE
DOS_DVKD	47	Y	N	VARCHAR2 (3 bytes)	<LONG>	FREQUENCY
DOS_ESKI_DOSYANUM	48	Y	N	VARCHAR2 (12 bytes)	<LONG>	HYBRID
DOS_ESKI_KREDI_ANAKOD	49	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_ESKI_KREDI_EKKOD	50	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DOS_ESKI_KREDI_KH	51	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_FIRMA_DEVIR_TAR_YYAG_...	52	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_FIRMA_KODU	53	Y	N	VARCHAR2 (5 bytes)	<LONG>	HYBRID
DOS_FIRMA_KONT_HARFI	54	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_FTF_ORANI	55	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_GARANTOR_YI_BANKA	56	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DOS_HAFSON_ACILKD	57	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_HAFSON_BAKIYE	58	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_ILK_VADEBITTAR_YYAG_D...	59	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_KAPAMA_TAR_YYAG_DT	60	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_KEFIL_SAY	61	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DOS_KONF_TEYIT_MHBRKD	62	Y	N	VARCHAR2 (4 bytes)	<LONG>	NONE
DOS_KOSGEB_FAIZ_ALINAN	63	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KOSGEB_IADE_FLAG	64	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KSGB_IADEFAIZ_TAR_YYA...	65	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KOSGEB_KAPALI_FAIZ	66	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_ACH_NO	67	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_BAZORAN_ETKI_KODU	68	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_BAZORAN_ETKI_TIPI	69	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_BAZORAN_VADE_SEC_...	70	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DOS_KRE_DTH_NO	71	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_EKSTRE_DEF_SIRA	72	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_EKSTRE_KODU	73	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_EKSTRETAR_YYAG_DT	74	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_EXIM_FZ_KATSAYI	75	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_EX_FZHES_BSTR_YYA...	76	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_EXIM_KUR	77	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_FAIZ_DEVRESI	78	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DOS_KRE_FAIZ_DEVRESI_YYAG...	79	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_FAIZ_HESABI_FLAG	80	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DOS_KRE_FAIZ_KODU	81	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DOS_KRE_FAIZ_ONAY_KODU	82	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_FAIZ_ONAY_YYAG_DT	83	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_FON_KODU	84	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_GECFAIZ_ORAN	85	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_FAIZ_MUHKD	86	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_KUR	87	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_KUR_REFN...	88	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_KUR_YYAG...	89	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_MUHKD	90	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_REFNO	91	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_SON_KUR	92	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_SON_KUR_...	93	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_REES_YYAG_DT	94	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_GEL_REESBAK	95	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_REESBAK_TL	96	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_REESTUT	97	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GEL_YILSONU_DVFAI...	98	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GERIVALR_FLAG	99	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_GID_FAIZ_MUHKD	100	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_KUR	101	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_KUR_REFN...	102	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_KUR_YYAG...	103	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_MUHKD	104	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_REFNO	105	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_SON_KUR	106	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_SON_KUR_...	107	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GID_REES_YYAG_DT	108	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_GID_REESBAK	109	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
DOS_KRE_GID_REESBAK_TL	110	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_GID_REESTUT	111	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
DOS_KRE_GID_YILSONU_DVFAI...	112	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_ILGILI_DOSYA	113	Y	N	VARCHAR2 (12 bytes)	<LONG>	NONE
DOS_KRE_KAPALI_DVADAT	114	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_KAPALI_FAIZSIZ_DV...	115	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_KAPALI_FAIZSIZ_TL...	116	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_KAPALI_GEL_DVFAIZ	117	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_KAPALI_GID_DVFAIZ	118	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_KAPALI_TLADAT	119	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_KAYNAK_KODU	120	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DOS_KRE_KULLAN_TUTAR	121	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
DOS_KRE_KULLANDIRMA	122	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_NEXT_BAZORAN_YYAG...	123	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_NEXT_FAIZTAR_YYAG...	124	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_KRE_ONAY_REES_BAS_YYA...	125	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_ONC_YILSONU_DVADA...	126	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_ONC_YILSONU_DVFAI...	127	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_PRIM_DVTUT	128	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_PRIM_REES_KUR	129	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_PRIM_YYAG_DT	130	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_REES_KARZARAR_HES...	131	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
DOS_KRE_REESKONT_ONAY_KOD...	132	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_SON_BAZORAN	133	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_SON_EKSTREBAK	134	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_SON_EKSTRENO	135	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_SON_FAIZTAR_YYAG_...	136	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_SON_SPREAD	137	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_SON_VADE	138	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DOS_KRE_TAAHHUT_KAPAMA_KO...	139	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_TAAHHUT_KAPANAN_T...	140	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_TAAHHUT_KAPAN_YYA...	141	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_TAAHHUT_TUTARI	142	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_TAAHHUT_VADESI_YY...	143	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_TAHAKKUK_ATILAN	144	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_TAHAKKUK_TAHSIL	145	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_TAHSISNO	146	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_TESV_BELGENO	147	Y	N	VARCHAR2 (10 bytes)	<LONG>	NONE
DOS_KRE_TESV_BELGETAR_YYA...	148	Y	N	DATE (7 bytes)	<LONG>	NONE
DOS_KRE_TESVIK_DURUMU	149	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_TOP_VADESONU_FAIZ...	150	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_VADE_SONRASI_REES...	151	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_VERGI_KODU	152	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_YILS_KAPALI_TLADA...	153	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_YILSONU_DVADAT	154	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_YILSONU_KUR	155	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_YILSONU_YYYY	156	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_MUHABIRKD	157	Y	N	VARCHAR2 (4 bytes)	<LONG>	HYBRID
DOS_MUHKD	158	Y	N	VARCHAR2 (8 bytes)	<LONG>	FREQUENCY
DOS_MUSTERINO	159	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_ONC_HAFSON_ACILKD	160	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_ONC_HAFSON_BAKIYE	161	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_ONCEKI_BAKIYE	162	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_OTO_TAKIP_FLAG	163	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_RAMKD	164	Y	N	VARCHAR2 (4 bytes)	<LONG>	NONE
DOS_RISK_KODU	165	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DOS_SEKTOR_KOD	166	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_SONHAR_SIRANO	167	Y	N	VARCHAR2 (4 bytes)	<LONG>	NONE
DOS_SONISTAR_YYAG_DT	168	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
DOS_TAHAKKUK_SAYISI	169	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_TAKIP_KODU	170	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_ULKE	171	Y	N	VARCHAR2 (3 bytes)	<LONG>	NONE
DOS_VADEBASTAR_YYAG_DT	172	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_VADEBITTAR_YYAG_DT	173	Y	N	DATE (7 bytes)	<LONG>	HYBRID
DOS_VASURE_1	174	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_VASURE_2	175	Y	N	VARCHAR2 (3 bytes)	<LONG>	NONE
DOS_YILSONU_BAKIYE	176	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KHES_RISK1_KOD	177	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KHES_KRED1_ANAKOD	178	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
DOS_KHES_KRED1_EKKOD	179	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DOS_KHES_KRED1_KH	180	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_KRE_ACAN_SUBE	181	Y	N	VARCHAR2 (4 bytes)	<LONG>	NONE
DOS_GERCEK_FAIZ_TIPI	182	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DOS_ADRES_1	183	Y	N	VARCHAR2 (28 bytes)	<LONG>	NONE
DOS_ADRES_2	184	Y	N	VARCHAR2 (33 bytes)	<LONG>	NONE
DOS_ISIM	185	Y	N	VARCHAR2 (40 bytes)	<LONG>	NONE
DOS_NAKIT_AKIS_KODU	186	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DOS_TRANSIT_TICARET_FLAG	187	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DOS_DOSYANUM	188	Y	N	VARCHAR2 (12 bytes)	<LONG>	HYBRID
DOS_AYSONU_GEL_REESTUT	189	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_AYSONU_GID_REESTUT	190	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DOS_KRE_SON_FAIZ_TAHAK_YY...	191	Y	N	DATE (7 bytes)	<LONG>	NONE