SELECT 
*
FROM ODS.LFN_KKB_LOAN_INFO 
WHERE
(
LOI_ACCOUNT_NUMBER = '4399DG700017' OR
LOI_CUSTOMER_NO = '31423373'
) AND
SNPST_DT = to_date('2019-04-01', 'YYYY-MM-DD'); 


SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	NONE
LOI_ID	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_CUSTOMER_NO	5	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_SCOPE_CODE	6	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_ACCOUNT_ID	7	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_ACCOUNT_NUMBER	8	Y	N	VARCHAR2 (15 bytes)	<LONG>	NONE
LOI_ACCOUNT_TYPE	9	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOI_CURRENCY_CODE	10	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
LOI_CREDIT_BALANCE	11	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_STATUS	12	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOI_CREATE_USER	13	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
LOI_CREATE_TIME	14	Y	N	TIMESTAMP(6) (11 bytes)	<LONG>	NONE
LOI_UPDATE_USER	15	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
LOI_UPDATE_TIME	16	Y	N	TIMESTAMP(6) (11 bytes)	<LONG>	NONE