SELECT *
FROM ODS.TRX_BDEFSDEP 
WHERE 
BDSSBKD = '4200' AND BDSMUSNO = '1000107'
ORDER BY BDSTARIH desc;

SEGCKEY	1	Y	N	VARCHAR2 (50 bytes)	<LONG>	HEIGHT BALANCED
BDSTARIH_DT	2	Y	N	TIMESTAMP(6) (11 bytes)	<LONG>	HEIGHT BALANCED
BDSTARIH	3	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_ZAMAN	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSSBKD	5	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
BDSMUSNO	6	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
BDSSIRANO	7	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
BDSMEMKD	8	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
BDSISLNO	9	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
BDSTRNKD	10	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
BDS_KSBKD	11	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_TD_KSBKD	12	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_TD_TRANKD	13	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
BDSVALOR	14	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSVALOR_DT	15	Y	N	DATE (7 bytes)	<LONG>	HEIGHT BALANCED
BDSBORCAL	16	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
BDSKOD4	17	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
BDSTUTARI	18	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
BDSBAKIYE	19	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSACIKL1	20	Y	N	VARCHAR2 (28 bytes)	<LONG>	HEIGHT BALANCED
BDS_ISLEM_KURU	21	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_DOVEND_ACIKL1	22	Y	N	VARCHAR2 (22 bytes)	<LONG>	NONE
BDS_DOV_BR_HESAP	23	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_RE_MUHKD_B	24	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
BDS_DOV_AL_HESAP	25	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_DOV_REFNO	26	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_RE_MUHKD_A	27	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
BDS_DOV_CEK_NO	28	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSACIKL2	29	Y	N	VARCHAR2 (33 bytes)	<LONG>	HEIGHT BALANCED
BDS_KHESAP_VAL_GAYC	30	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_KHESAP_VAL_GAY	31	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_KHESAP_VAL_GAY_DT	32	Y	N	DATE (7 bytes)	<LONG>	NONE
BDS_KHESAP_VAL_CC	33	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_DOV_MUHKD_A	34	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
BDS_DOV_MUHKD_B	35	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
BDS_IPTAL_SIRANO	36	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_TD_IPT_KOD	37	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
BDS_APARA_KURFARKI_FON_X	38	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
BDS_APARA_KURFARKI_FON	39	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSSENCEKTUT	40	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSKALANSENCEK	41	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSSENCEKKODU	42	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
BDSBASTAR	43	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSBASTAR_DT	44	Y	N	DATE (7 bytes)	<LONG>	NONE
BDS_DV_ISLEM_TUT	45	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSBITTAR	46	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDSBITTAR_DT	47	Y	N	DATE (7 bytes)	<LONG>	NONE
BDSISLEM_TIPI	48	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
BDSISLEM_TURU	49	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
BDS_KANAL_KODU	50	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
BDS_KARSI_HESAP_TIP	51	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
BDS_KARSI_HESAP_SUBE	52	Y	N	NUMBER (22 bytes)	<LONG>	NONE
BDS_KARSI_HESAP_HESAPNO	53	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
BDS_KARSI_HESAP_HESX	54	Y	N	NUMBER (22 bytes)	<LONG>	NONE
SRC_DT	55	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	56	Y	N	DATE (7 bytes)	<LONG>	HEIGHT BALANCED
UNQ_RT_ID_IN_SRC_STM	57	Y	N	VARCHAR2 (50 bytes)	<LONG>	NONE
BDS_TOD	58	Y	N	VARCHAR2 (16 bytes)	<LONG>	HEIGHT BALANCED