SELECT 
ER.ACEXT_BRANCH_CODE,
ER.ACEXT_ACCOUNT_NUMBER,
ACR.ACCUS_CUSTOMER_ID,
ER.ACEXT_ACCOUNT_ID,
ER.ACEXT_ACCOUNT_TYPE_ID,
ER.ACEXT_IBAN
FROM
ODS.HYM_ACCOUNT_EXTERNAL_REF ER,
ODS.HYM_ACCOUNT_CUSTOMER_REL ACR
WHERE 
ER.ACEXT_BRANCH_CODE = 4399 AND ER.ACEXT_ACCOUNT_NUMBER = 700701 AND
ER.ACEXT_ACCOUNT_ID = ACR.ACCUS_ACCOUNT_ID AND
ER.SNPST_DT = TO_DATE('2019-04-01', 'YYYY-MM-DD') AND
ACR.SNPST_DT = TO_DATE('2019-04-01', 'YYYY-MM-DD');

SCHESAP.ACCOUNT_EXTERNAL_REF
ACEXT_ACCOUNT_TYPE_ID	1	N	Y	SMALLINT	
ACEXT_BRANCH_CODE	2	N	Y	SMALLINT	
ACEXT_ACCOUNT_NUMBER	3	N	Y	INTEGER 	
ACEXT_ADDITIONAL_KEY	4	N	Y	VARCHAR (50)	
ACEXT_ACCOUNT_ID	5	N	N	BIGINT  	
ACEXT_EXPIRE_TS	6	Y	N	TIMESTMP	
ACEXT_IBAN	7	N	N	CHAR    (26)	
ACEXT_ACCOUNT_LOCATION	8	N	N	CHAR    (1)	
ACEXT_PARTITION_INDEX	9	N	N	SMALLINT

SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	NONE
LOAN_PARTITION_INDEX	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_ACC_ID	5	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_CRY_FX_F	6	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_CLOSE_REASON	7	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
LOAN_VAL_PRVLDG_CODE	8	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_INSTALLMENT_COUNT	9	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_FLEXIBLE_F	10	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_SCHEDULED_CLOSING_DT	11	Y	N	DATE (7 bytes)	<LONG>	NONE
LOAN_CAMPAIGN_PD_ID	12	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_NKP_CODE	13	Y	N	VARCHAR2 (20 bytes)	<LONG>	NONE
LOAN_NEXT_INT_DT	14	Y	N	DATE (7 bytes)	<LONG>	NONE
LOAN_INT_PER	15	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_INT_PER_TYPE	16	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_SRC_CODE	17	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_OPENING_CRY	18	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_AUTO_PROCEEDING_F	19	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_EXPORT_CODE	20	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_BLOCKAGE_CODE	21	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_TRX_AUTH_CODE	22	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
LOAN_INT_TERM	23	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
LOAN_COMMERCIAL_F	24	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_APP_F	25	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_PP_LOC	26	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_TAX_CODE	27	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_FUND_CODE	28	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOAN_INTER_BRANCH	29	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOAN_REFINANSMAN_F	30	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE

SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	NONE
ODS_MUSTERI_NO	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACCUS_ID	5	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACCUS_CUSTOMER_ID	6	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACCUS_ACCOUNT_ID	7	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACCUS_TYPE	8	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
ACCUS_START_DATE	9	Y	N	DATE (7 bytes)	<LONG>	NONE
ACCUS_END_DATE	10	Y	N	DATE (7 bytes)	<LONG>	NONE
ACCUS_NICK_NAME	11	Y	N	VARCHAR2 (30 bytes)	<LONG>	NONE
ACCUS_APPROVAL_TYPE	12	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
ACCUS_STATUS	13	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
ACCUS_FIRST_ACCOUNT_FLAG	14	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
ACCUS_INVESTMENT_FLAG	15	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
ACCUS_ARR_TYPE	16	Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STSJ1QHPI$2AHYGGI9#73...		Y	N	NUMBER (22 bytes)	<LONG>	NONE

SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	NONE
ACREL_ID	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACREL_ARR_TYPE	5	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACREL_ACCOUNT_ID	6	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACREL_REL_TYPE	7	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACREL_REL_ARR_TYPE	8	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
ACREL_REL_ACCOUNT_ID	9	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACREL_START_DATE	10	Y	N	DATE (7 bytes)	<LONG>	NONE
ACREL_END_DATE	11	Y	N	DATE (7 bytes)	<LONG>	NONE
ACREL_STATUS	12	Y	N	CHAR (1 bytes)	<LONG>	NONE
ODS_DURUM_KODU	13	Y	N	VARCHAR2 (10 bytes)	<LONG>	NONE
SYS_STS#CAN38N#Y7W#WI9EDD...		Y	N	NUMBER (22 bytes)	<LONG>	NONE

SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	HYBRID
PPL_ACC_ID	4	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
PPL_APP_ID	5	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_AVG_DURATION	6	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_BRANCH_CODE	7	Y	N	NUMBER (22 bytes)	<LONG>	HYBRID
PPL_CREATE_TSTP	8	Y	N	DATE (7 bytes)	<LONG>	HYBRID
PPL_CRY_CODE	9	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_CUST_NO	10	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_DISBURSMNT_DT	11	Y	N	DATE (7 bytes)	<LONG>	NONE
PPL_FUND_CODE	12	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_FUND_RATE	13	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_INSTALLMENT_AMT	14	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_INT_RATE	15	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_LOAN_AMT	16	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_MTR_DAY_COUNT	17	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_MTR_TIME	18	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_PD_ID	19	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_PER_SCALE	20	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_PLAN_ID	21	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_PLAN_TYPE	22	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
PPL_PREPAID_INT_BY_CUST	23	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_PREPAID_INT_BY_FIRM	24	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_PREV_VERSION	25	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_REASON_CODE	26	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
PPL_ST	27	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
PPL_START_DT	28	Y	N	DATE (7 bytes)	<LONG>	NONE
PPL_TAX_CODE	29	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_TAX_FREE_TERMS	30	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_TAX_RATE	31	Y	N	NUMBER (22 bytes)	<LONG>	NONE
PPL_UPD_TSTP	32	Y	N	DATE (7 bytes)	<LONG>	NONE
PPL_VERSION	33	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
