SELECT DISTINCT ER.ACEXT_BRANCH_CODE, ER.ACEXT_ACCOUNT_NUMBER, PP.PPL_PLAN_ID
FROM 
STG.PP_PYMT_PLAN PP, 
ODS.HYM_ACCOUNT_EXTERNAL_REF ER 
WHERE 
ER.ACEXT_ACCOUNT_TYPE_ID = 14 AND 
ER.ACEXT_ACCOUNT_ID = PP.PPL_ACC_ID AND 
PP.PPL_ST = 'A'
AND ( ER.SNPST_DT = TO_DATE('2019-06-01', 'YYYY-MM-DD') AND 
PP.SNPST_DT = TO_DATE('2019-06-13', 'YYYY-MM-DD') )
AND (ER.ACEXT_BRANCH_CODE = 1420);