SELECT DISTINCT
T2.LOI_CUSTOMER_NO,
T2.LOI_SCOPE_CODE, 
T2.LOI_CURRENCY_CODE,
T1.ACEXT_BRANCH_CODE,
T1.ACEXT_ADDITIONAL_KEY,
T1.ACEXT_ACCOUNT_NUMBER, 		
T2.LOI_CREDIT_BALANCE
FROM 
ODS.HYM_ACCOUNT_EXTERNAL_REF T1,
ODS.LFN_KKB_LOAN_INFO T2 
WHERE T1.ACEXT_ACCOUNT_ID = T2.LOI_ACCOUNT_ID
AND T1.ACEXT_EXPIRE_TS IS NULL  
AND T2.LOI_STATUS <> 'P'                        
AND T1.SNPST_DT = to_date('2019-09-01', 'YYYY-MM-DD')
AND T2.SNPST_DT = to_date('2019-09-01', 'YYYY-MM-DD')
ORDER BY 1 ASC, 2 ASC;

SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	FREQUENCY
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	NONE
LOI_ID	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_CUSTOMER_NO	5	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_SCOPE_CODE	6	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_ACCOUNT_ID	7	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_ACCOUNT_NUMBER	8	Y	N	VARCHAR2 (15 bytes)	<LONG>	NONE
LOI_ACCOUNT_TYPE	9	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOI_CURRENCY_CODE	10	Y	N	NUMBER (22 bytes)	<LONG>	FREQUENCY
LOI_CREDIT_BALANCE	11	Y	N	NUMBER (22 bytes)	<LONG>	NONE
LOI_STATUS	12	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
LOI_CREATE_USER	13	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
LOI_CREATE_TIME	14	Y	N	TIMESTAMP(6) (11 bytes)	<LONG>	NONE
LOI_UPDATE_USER	15	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
LOI_UPDATE_TIME	16	Y	N	TIMESTAMP(6) (11 bytes)	<LONG>	NONE

HYM_ACCOUNT_EXTERNAL_REF 
SNPST_DT	1	Y	N	DATE (7 bytes)	<LONG>	NONE
SRC_DT	2	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	3	Y	N	DATE (7 bytes)	<LONG>	NONE
ODS_SUBE_KODU	4	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ODS_HESAP_NO	5	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACEXT_ACCOUNT_TYPE_ID	6	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACEXT_BRANCH_CODE	7	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACEXT_ACCOUNT_NUMBER	8	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACEXT_ADDITIONAL_KEY	9	Y	N	VARCHAR2 (50 bytes)	<LONG>	NONE
ACEXT_ACCOUNT_ID	10	Y	N	NUMBER (22 bytes)	<LONG>	NONE
ACEXT_EXPIRE_TS	11	Y	N	DATE (7 bytes)	<LONG>	NONE
ACEXT_IBAN	12	Y	N	VARCHAR2 (26 bytes)	<LONG>	NONE
ACEXT_ACCOUNT_LOCATION	13	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
ACEXT_PARTITION_INDEX	14	Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STS9ZKKRO7JHJB#PAQ2XH...		Y	N	NUMBER (22 bytes)	<LONG>	NONE