SELECT * FROM ODS.TRX_DOSYAHAR T1 WHERE T1.DSH_DOSYANUM = '1255DA400042' ORDER BY 4 ASC;



SEGCKEY	1	N	N	VARCHAR2 (50 bytes)	<LONG>	HEIGHT BALANCED
DSH_ISTAR_YYAG_DT	2	N	N	DATE (7 bytes)	<LONG>	HEIGHT BALANCED
DSH_ISTAR_YYAG	3	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
DSH_DOSYANUM	4	Y	N	VARCHAR2 (12 bytes)	<LONG>	NONE
DSH_DOSYANUM_SBKD	5	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
DSH_DOSYANUM_TIPI	6	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DSH_DOSYANUM_SIRANO	7	Y	N	VARCHAR2 (6 bytes)	<LONG>	HEIGHT BALANCED
DSH_HARSIRA	8	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
DSH_HARTIP	9	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DSH_BOALK	10	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DSH_TRANKD	11	Y	N	VARCHAR2 (2 bytes)	<LONG>	FREQUENCY
DSH_ISLEMTUR	12	Y	N	VARCHAR2 (4 bytes)	<LONG>	NONE
DSH_TELID	13	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
DSH_SEQNO	14	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
DSH_ISTIME	15	Y	N	NUMBER (22 bytes)	<LONG>	HEIGHT BALANCED
DSH_FZO_TARIH1_YYAG_DT	16	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_FZO_TARIH1_YYAG	17	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_TARIH2_YYAG_DT	18	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_FZO_TARIH2_YYAG	19	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_FAIZ_KODU	20	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DSH_FZO_BAZ_ORAN	21	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_SABIT_ORAN	22	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_SPREAD	23	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_BANKA_PAYI	24	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_ESKI_FAIZ_DEVRESI	25	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DSH_FZO_YENI_FAIZ_DEVRESI	26	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DSH_FZO_ESKI_SON_FAIZ_YYA...	27	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_FZO_ESKI_SON_FAIZ_YYA...	28	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_YENI_SON_FAIZ_YYA...	29	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_FZO_YENI_SON_FAIZ_YYA...	30	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FZO_DEGISEN_TIPI	31	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_KHES_ISLEM	32	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_KHES_MUHKD	33	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
DSH_KHES_KREDI_KODU	34	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DSH_KHES_KREDI_KODU_MAIN	35	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_KHES_KREDI_KODU_KH	36	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_KHES_KREDI_KODU_EK	37	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ARACI_SBKD	38	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ACILKD	39	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_ACIKL1	40	Y	N	VARCHAR2 (35 bytes)	<LONG>	NONE
DSH_DOSYA_TURU	41	Y	N	VARCHAR2 (1 bytes)	<LONG>	FREQUENCY
DSH_ACILBAK	42	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_VADEBASTAR_YYAG_DT	43	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_VADEBASTAR_YYAG	44	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_VADEBITTAR_YYAG_DT	45	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_VADEBITTAR_YYAG	46	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_RAMKD	47	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_MUHABIRKD	48	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_FIRMAKD	49	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DSH_ULKE	50	Y	N	VARCHAR2 (2 bytes)	<LONG>	NONE
DSH_ITH_ACILBAK	51	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_MUHKD	52	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
DSH_ITH_KHES_MUHKD	53	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
DSH_ITH_KHES_KREDI_KODU	54	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DSH_ITH_KREDI_KODU_MAIN	55	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_KREDI_KODU_KH	56	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_ITH_KREDI_KODU_EK	57	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_RAMKD	58	Y	N	VARCHAR2 (4 bytes)	<LONG>	NONE
DSH_POL_TARIH1_ESKI_YYAG_...	59	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_POL_TARIH1_ESKI_YYAG	60	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_POL_TARIH2_ESKI_YYAG_...	61	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_POL_TARIH2_ESKI_YYAG	62	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_POL_TUTAR_ESKI	63	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_POL_BELGENO_ESKI	64	Y	N	VARCHAR2 (12 bytes)	<LONG>	NONE
DSH_POL_DURUMKD_ESKI	65	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_ACIKL2	66	Y	N	VARCHAR2 (35 bytes)	<LONG>	NONE
DSH_POL_TARIH1_YENI_YYAG_...	67	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_POL_TARIH1_YENI_YYAG	68	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_POL_TARIH2_YENI_YYAG_...	69	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_POL_TARIH2_YENI_YYAG	70	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_POL_TUTAR_YENI	71	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_POL_BELGENO_YENI	72	Y	N	VARCHAR2 (12 bytes)	<LONG>	NONE
DSH_POL_DURUMKD_YENI	73	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_ITH_AKRVADE_YYAG_DT	74	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_ITH_AKRVADE_YYAG	75	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_YUKVADE_YYAG_DT	76	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_ITH_YUKVADE_YYAG	77	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_VADE_YYAG_DT	78	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_ITH_VADE_YYAG	79	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_MARJ	80	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_BLOKETUT	81	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_ITH_BLOKE_DVKD	82	Y	N	VARCHAR2 (3 bytes)	<LONG>	NONE
DSH_ITH_KREDI_DURUM	83	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_ITH_TESVIK_DURUM	84	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_ITH_MAL_GEL_ULKE	85	Y	N	VARCHAR2 (3 bytes)	<LONG>	NONE
DSH_IHR_AKRVADE_YYAG_DT	86	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_IHR_AKRVADE_YYAG	87	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_IHR_AKR_ACILTAR_YYAG_...	88	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_IHR_AKR_ACILTAR_YYAG	89	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_IHR_YUKVADE_YYAG_DT	90	Y	N	DATE (7 bytes)	<LONG>	NONE
DSH_IHR_YUKVADE_YYAG	91	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_IHR_KREDI_DURUM	92	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_IHR_TEYIT_MHBRKD	93	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_IHR_MAL_GIT_ULKE	94	Y	N	VARCHAR2 (3 bytes)	<LONG>	NONE
DSH_KRE_FAIZOR	95	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_KRE_FAIZTOP	96	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_KRE_KULLAN_TUTAR	97	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_KRE_TRANS_TUTAR	98	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_KRE_KULLANDIRMA	99	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_TEM_KONU	100	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_TEM_GARANTOR_YI_BANKA	101	Y	N	VARCHAR2 (6 bytes)	<LONG>	NONE
DSH_DURUM_KODU	102	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
DSH_ESKI_HARSIRA	103	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_VUK_BELGENOX	104	Y	N	VARCHAR2 (8 bytes)	<LONG>	NONE
DSH_VUK_BELGENO	105	Y	N	NUMBER (22 bytes)	<LONG>	NONE
DSH_KANAL_KODU	106	Y	N	VARCHAR2 (1 bytes)	<LONG>	NONE
SRC_DT	107	Y	N	DATE (7 bytes)	<LONG>	NONE
UPD_DT	108	Y	N	DATE (7 bytes)	<LONG>	NONE
UNQ_RT_ID_IN_SRC_STM	109	Y	N	VARCHAR2 (50 bytes)	<LONG>	NONE
SYS_STS8R34F0BG2Y0$245XVL...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STSZU53X_WQK4MSLNW9T_...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STS4$O$6JI#Z1LI42IND8...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STSU#A40L#GFZX$2UI53M...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STS2D0HPQ0X1117GI$GAK...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STSHI2FH6PDU0$N7F4PIS...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STSLUNTJ_2R_O_OI$SA7U...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STSYXXMQAFF717Q_TXEYB...		Y	N	NUMBER (22 bytes)	<LONG>	NONE
SYS_STS8JH5KJJS$JV8QPC4P7...		Y	N	NUMBER (22 bytes)	<LONG>	NONE