SELECT
concat(to_char(bc_sbkd), lpad(to_char(bc_musno),7,'0')) as bchkey,
to_char(bc_dovkodu) as bc_dovkodu,
to_char(bc_acilkd1) as bc_acilkd1,
to_char(bc_acilkd3) as bc_acilkd3,
to_char(bc_acilkd6) as bc_acilkd6,
to_char(bc_acilkd8) as bc_acilkd8,
case when trim(to_char(bc_dovend_mekanize_kd)) is null then 'H' else to_char (bc_dovend_mekanize_kd) end as bc_dovend_mekanize_kd,
to_char(bc_blokekd) as bc_blokekd,
case when to_char(bc_faiz_devresi) in ('1A','3A','6A','1Y','H1','H3','H6','HY') then 'PR' else to_char(bc_faiz_devresi) end as bc_faiz_devresi,
to_char(bc_faizoran_tipi)		as bc_faizoran_tipi,
to_char(bc_ihbar_suresi)        as bc_ihbar_suresi,
to_char(bc_firma_devir_tar_yyag) as bc_firma_devir_tar_yyag,
to_char(bc_kredi_limiti)        as bc_kredi_limiti,
to_char(bc_kredi_limiti_dv)     as bc_kredi_limiti_dv,
to_char(bc_faizlibak)           as bc_faizlibak,
to_char(bc_faizlibak_dv)        as bc_faizlibak_dv,
to_char(bc_bforani,'FM09.90')             as bc_bforani,
to_char(bc_maliyet_orani,'FM09.90')       as bc_maliyet_orani,
to_char(bc_banka_payi)          as bc_banka_payi,
to_char(bc_komorani,'FM09.90')            as bc_komorani,
to_char(bc_cek_marjorani,'FM09.90')       as bc_cek_marjorani,
to_char(bc_senet_marjorani,'FM09.90')     as bc_senet_marjorani,
to_char(bc_aciltar_yyag)        as bc_aciltar_yyag,
to_char(bc_kapatar_yyag)        as bc_kapatar_yyag,
to_char(bc_next_faiztar_yyag)   as bc_next_faiztar_yyag,
to_char(bc_sonistar_yyag)       as bc_sonistar_yyag,
to_char(bc_gfaiz_oran, 'FM09.90')   as bc_gfaiz_oran,
to_char(bc_exim_firmakd)        as bc_exim_firmakd,
to_char(bc_exim_sirano)         as bc_exim_sirano,
case when to_char(bc_acilis_kuru) = '0' then to_char('1') else to_char(bc_acilis_kuru) end as bc_acilis_kuru,
to_char(bc_tx_yetki_kodu)       as bc_tx_yetki_kodu,
to_char(bc_tmo_urun_kodu)       as bc_tmo_urun_kodu,
to_char(bc_taah_kapama_yetkikodu) as bc_taah_kapama_yetkikodu,
to_char(bc_oto_takip_flag)     as  bc_oto_takip_flag,
to_char(bc_kredikod_main)      as  bc_kredikod_main,
case when trim(to_char(bc_ilgili_policeno_sbkd)) is null then '0' else trim(to_char(bc_ilgili_policeno_sbkd)) end as bc_ilgili_policeno_sbkd,
to_char(bc_ilgili_policeno_tipi) as bc_ilgili_policeno_tipi,
case when trim(to_char(bc_ilgili_policeno_cuzdan)) is null then '0' else trim(to_char(bc_ilgili_policeno_cuzdan)) end as bc_ilgili_policeno_cuzdan,
to_char(bc_ihr_durum_kod) as bc_ihr_durum_kod,
to_char(bc_kaynak_kodlari) as bc_kaynak_kodlari,
to_char(bc_transit_ticaret_flag) as bc_transit_ticaret_flag,
to_char(bc_alckhesno) as bc_alckhesno,
to_char(bc_yeni_bchno) as bc_yeni_bchno,	 
case when trim(to_char(bc_ilgili_dosyano_sbkd)) is null then 'X0' when trim(to_char(bc_ilgili_dosyano_sbkd)) = 0 then 'X0' else bc_ilgili_dosyano_sbkd end as bc_ilgili_dosyano_sbkd,  
case when trim(to_char(bc_ilgili_dosyano_tipi)) is null then 'X0' else bc_ilgili_dosyano_tipi end as bc_ilgili_dosyano_tipi,  
case when trim(to_char(bc_ilgili_dosyano_sirano)) is null then 'X0' when trim(to_char(bc_ilgili_dosyano_sirano)) = 0 then 'X0' else bc_ilgili_dosyano_sirano end as bc_ilgili_dosyano_sirano,    
case when trim(to_char(bc_fiyat_refno)) is null then 'X0' else concat('X', substr(bc_fiyat_refno,2,11)) end as bc_fiyat_refno,
to_char(bc_aval_3n_blkrefno) as bc_aval_3n_blkrefno,  
to_char(bc_aysonu_bakiye) as bc_aysonu_bakiye
from stg.borclure where to_char(bc_acilkd1) = '2' and snpst_dt = to_date('2019-09-15', 'YYYY-MM-DD') 
and (bc_sbkd = 1420 or bc_sbkd = 1000151)
ORDER BY 1 ASC ,2 ASC;