select pgmname, prjname, mdltype from scdegisk.moduls where pgmname in 
SELECT DISTINCT PROGNAME FROM SCDEGISK.CPYFIELD WHERE COPYNAME = 'EMAIDREC';
SELECT PROGRAM1 FROM SCDEGISK.PGMDRIVE where PROGRAM2 = 'SB3NTRAN' AND PROGRAM1 LIKE 'PS%';