select pgmname, prjname, mdltype from scdegisk.moduls where pgmname in 
(
SELECT DISTINCT PROGRAM1 FROM SCDEGISK.PGMDRIVE where PROGRAM1 like 'PS%' AND PROGRAM2 IN 
(SELECT DISTINCT PROGNAME FROM SCDEGISK.CPYFIELD WHERE COPYNAME = 'DEBUGMOD')
) and MDLTYPE = 'COBOL';